### ISSUE TITLE
Problem with zoom for list of maps

### ISSUE THREAD

**Issue by petrtcoi** [gribnoysup/react-yandex-maps#121] opened 2018-11-13 11:29 UTC
I have a list of maps to show. 
const zoom = distance / 15;
<Map
      center={startLocation}
     zoom={zoom}
     height={200}
     width={'100%'}
/>

It works fine for the first element. 
But next element show map with too large zoom.

I have attached screenshots to show. All zoom variables about 15-18 here. But you can see that it is now works properly. https://drive.google.com/open?id=1jX4Co_qmUtyzRc5X058gbGOkhMkAx4qU

Looks like there are mistake with async request? How It can be solved?

**Comment by gribnoysup** [comment] 2018-11-13 13:14
Hi @petrtcoi! Can you please provide a more complete example of the issue?

**Comment by mmarkelov** [comment] 2018-11-13 13:41
@petrtcoi I am confused, cause you are using **yandex-map-react** package.

**Comment by petrtcoi** [comment] 2018-11-13 13:50
Sorry (
I have tried with another library and got the same problem;

`Post.js

import { YMaps, Map } from 'react-yandex-maps';

class Post extends React.Component {
render(
   const post = this.props.post;
   const zoom = Math.floor(post.distance / 16);

  return(
            <div className="row justify-content-center mx-0 ">
                <div className="col-xs-12 col-sm-10 col-md-6 px-0 mx-0" >
                    <YMaps>
                        <div>
                          <Map defaultState={{ center: startLocation, zoom: zoom }} />
                        </div>
                     </YMaps>
                </div>
            </div>


        );

)
}
`

**Comment by petrtcoi** [comment] 2018-11-13 13:52
```
return(
            <div className="row justify-content-center mx-0 ">
                <div className="col-xs-12 col-sm-10 col-md-6 px-0 mx-0" >

                    <YMaps>
                        <div>
                          <Map defaultState={{ center: startLocation, zoom: zoom }} />
                        </div>
                     </YMaps>


                </div>
            </div>


        );
```

**Comment by mmarkelov** [comment] 2018-11-13 14:16
@petrtcoi Sorry, but I can’t understand what do you actually want. If you want all your maps have one zoom, you should provide one zoom for all your map instances.

**Comment by petrtcoi** [comment] 2018-11-13 14:17
I want all maps have different zoom. I calculate it for each map element.
But looks like that is I render a list of maps, value of zoom influence on next map's zoom.

**Comment by gribnoysup** [comment] 2018-11-13 16:48
Sorry, @petrtcoi, no matter how I try, I can't reproduce your issue. I created a small demo that renders a bunch of `Map` components with different zoom. As you can see, all of them have zoom levels properly applied:

[![Edit n5rk87w8np](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n5rk87w8np)

I don't think we can help you with your issue unless you provide an example with reproduction

**Comment by mmarkelov** [comment] 2018-11-13 17:15
@petrtcoi Youp! I also tried to reproduce the issue, but seems like it is OK:

[![Edit 4zx4o488w7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4zx4o488w7)

**Comment by petrtcoi** [comment] 2018-11-13 18:52
Thank you for the time... Look like mistake in my rest code. Not in the lib..
Thanks again!

**Comment by mmarkelov** [comment] 2018-11-13 19:23
@petrtcoi you are welcome. I suppose we can close this issue.

**Closed by mmarkelov** 2018-11-13 19:23 UTC
Labels: needs more info
